### PR TITLE
fix: remove heading icons froms menu dropdown

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Could you explain the motivation for this change? Just for future reference.

**Comment by ojeytonwilliams** [comment]
Okay, so we don't want icons?

**Comment by Sembauke** [comment]
I guess not for the menu items themselves.

**Review by ojeytonwilliams — APPROVED** [review]
Thanks for clarifying. This LGTM :+1:

**Review by ojeytonwilliams — APPROVED** [review]

**Pull request merged**
